# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d0de1802e4ad1f249118ef52217d452b7425cc65deab0755c06862a6480d00fe95a5fbebde2bc27de0e3ab9aca30a133f7de6c66ded2f72b4b0fe76d23f2145

test:
  secret_key_base: 3a7b6a3c304292d568b80ac94c827496b5272474d1d2e2236e68f79bae9816c1b92ac748876854a771f24c25a60bd989df4fdb260b5bd4ef2cd76362e7cafc6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
